package com.hbm.datagen;

import com.hbm.blocks.NtmBlocks;
import com.hbm.main.NuclearTechMod;
import net.minecraft.core.HolderLookup;
import net.minecraft.data.PackOutput;
import net.minecraft.tags.BlockTags;
import net.minecraft.world.level.block.Blocks;
import net.neoforged.neoforge.common.data.BlockTagsProvider;
import net.neoforged.neoforge.common.data.ExistingFileHelper;

import java.util.concurrent.CompletableFuture;

import static com.hbm.inventory.NtmTags.Blocks.*;
import static net.neoforged.neoforge.common.Tags.Blocks.PUMPKINS;

public class NtmBlockTagProvider extends BlockTagsProvider {

    public NtmBlockTagProvider(PackOutput output, CompletableFuture<HolderLookup.Provider> lookupProvider, ExistingFileHelper existingFileHelper) {
        super(output, lookupProvider, NuclearTechMod.MODID, existingFileHelper);
    }

    @Override
    @SuppressWarnings("unchecked") // no
    protected void addTags(HolderLookup.Provider provider) {

        this.tag(PLANTS)
                .addTags(
                        BlockTags.FLOWERS,
                        BlockTags.SAPLINGS,
                        BlockTags.CROPS,
                        PUMPKINS
                )
                .add(
                        Blocks.SHORT_GRASS,
                        Blocks.FERN,
                        Blocks.DEAD_BUSH,
                        Blocks.VINE,
                        Blocks.TALL_GRASS,
                        Blocks.LARGE_FERN
                );

        // im probably dumb but i dont know any tags like this
        tag(ACTUALLY_STONE)
                .add(Blocks.COAL_ORE)
                .add(Blocks.IRON_ORE)
                .add(Blocks.COPPER_ORE)
                .add(Blocks.LAPIS_ORE)
                .add(Blocks.DIAMOND_ORE)

                .add(Blocks.DEEPSLATE_COAL_ORE)
                .add(Blocks.DEEPSLATE_IRON_ORE)
                .add(Blocks.DEEPSLATE_COPPER_ORE)
                .add(Blocks.DEEPSLATE_LAPIS_ORE)
                .add(Blocks.DEEPSLATE_DIAMOND_ORE)

                .add(Blocks.GRANITE)
                .add(Blocks.ANDESITE)
                .add(Blocks.DIORITE)
                .add(Blocks.DEEPSLATE)
                .add(Blocks.TUFF)
                .add(Blocks.COBBLESTONE)
                .add(Blocks.SANDSTONE)

                .add(NtmBlocks.BRICK_CONCRETE.get())
                .add(NtmBlocks.BRICK_CONCRETE_CRACKED.get())
                .add(NtmBlocks.BRICK_CONCRETE_BROKEN.get())
                .add(NtmBlocks.BRICK_CONCRETE_MOSSY.get())
                .add(NtmBlocks.BRICK_CONCRETE_MARKED.get())
                .add(NtmBlocks.BRICK_LIGHT.get())

                .add(Blocks.STONE);

        tag(GROUND)
                .add(Blocks.GRASS_BLOCK)
                .add(Blocks.MUD)
                .add(Blocks.MUDDY_MANGROVE_ROOTS)
                .add(Blocks.MANGROVE_ROOTS)
                .add(Blocks.GRAVEL)
                .add(Blocks.DIRT_PATH)
                .add(Blocks.MYCELIUM)
                .add(Blocks.SAND)
                .add(Blocks.DIRT);

        this.tag(BlockTags.MINEABLE_WITH_PICKAXE)
                .add(
                        NtmBlocks.ORE_BASALT.get(),

                        NtmBlocks.ORE_OIL.get(),
                        NtmBlocks.ORE_OIL_EMPTY.get(),
                        NtmBlocks.ORE_OIL_SAND.get(),
                        NtmBlocks.ORE_BEDROCK_OIL.get(),
                        NtmBlocks.ORE_URANIUM.get(),
                        NtmBlocks.ORE_URANIUM_DEEPSLATE.get(),
                        NtmBlocks.ORE_URANIUM_SCORCHED.get(),
                        NtmBlocks.ORE_BERYLLIUM.get(),
                        NtmBlocks.ORE_BERYLLIUM_DEEPSLATE.get(),
                        NtmBlocks.ORE_TUNGSTEN.get(),
                        NtmBlocks.ORE_TUNGSTEN_DEEPSLATE.get(),
                        NtmBlocks.ORE_TITANIUM.get(),
                        NtmBlocks.ORE_TITANIUM_DEEPSLATE.get(),
                        NtmBlocks.ORE_LEAD.get(),
                        NtmBlocks.ORE_LEAD_DEEPSLATE.get(),
                        NtmBlocks.ORE_ALUMINIUM.get(),
                        NtmBlocks.ORE_ALUMINIUM_DEEPSLATE.get(),
                        NtmBlocks.ORE_ASBESTOS.get(),
                        NtmBlocks.ORE_ASBESTOS_DEEPSLATE.get(),
                        NtmBlocks.ORE_THORIUM.get(),
                        NtmBlocks.ORE_THORIUM_DEEPSLATE.get(),
                        NtmBlocks.ORE_NITER.get(),
                        NtmBlocks.ORE_NITER_DEEPSLATE.get(),
                        NtmBlocks.ORE_COBALT.get(),
                        NtmBlocks.ORE_COBALT_DEEPSLATE.get(),
                        NtmBlocks.ORE_CINNABAR.get(),
                        NtmBlocks.ORE_CINNABAR_DEEPSLATE.get(),
                        NtmBlocks.ORE_FLUORITE.get(),
                        NtmBlocks.ORE_FLUORITE_DEEPSLATE.get(),
                        NtmBlocks.ORE_METEOR_IRON.get(),
                        NtmBlocks.ORE_METEOR_COBALT.get(),
                        NtmBlocks.ORE_METEOR_ALUMINIUM.get(),
                        NtmBlocks.ORE_METEOR_COPPER.get(),
                        NtmBlocks.ORE_METEOR_RARE.get(),
                        NtmBlocks.ORE_RARE.get(),
                        NtmBlocks.ORE_RARE_DEEPSLATE.get(),
                        NtmBlocks.ORE_SULFUR.get(),
                        NtmBlocks.ORE_SULFUR_DEEPSLATE.get(),
                        NtmBlocks.ORE_LIGNITE.get(),
                        NtmBlocks.ORE_DEEPSLATE_LIGNITE.get(),
                        NtmBlocks.ORE_SCHRABIDIUM.get(),
                        NtmBlocks.ORE_NETHER_URANIUM.get(),
                        NtmBlocks.ORE_NETHER_URANIUM_SCORCHED.get(),
                        NtmBlocks.ORE_NETHER_PLUTONIUM.get(),
                        NtmBlocks.ORE_NETHER_SCHRABIDIUM.get(),
                        NtmBlocks.ORE_TIKITE.get(),
                        NtmBlocks.ORE_GNEISS_URANIUM.get(),
                        NtmBlocks.ORE_GNEISS_URANIUM_SCORCHED.get(),
                        NtmBlocks.ORE_GNEISS_SCHRABIDIUM.get(),
                        NtmBlocks.ORE_SELLAFIELD_EMERALD.get(),
                        NtmBlocks.ORE_SELLAFIELD_DIAMOND.get(),
                        NtmBlocks.DECO_RED_COPPER.get(),
                        NtmBlocks.DECO_ASBESTOS.get(),
                        NtmBlocks.DECO_ALUMINIUM.get(),
                        NtmBlocks.DECO_TUNGSTEN.get(),
                        NtmBlocks.DECO_TITANIUM.get(),
                        NtmBlocks.DECO_LEAD.get(),
                        NtmBlocks.DECO_RUSTY_STEEL.get(),
                        NtmBlocks.DECO_STEEL.get(),
                        NtmBlocks.DECO_BERYLLIUM.get(),
                        NtmBlocks.DECONTAMINATOR.get(),
                        NtmBlocks.BARREL_CORRODED.get(),
                        NtmBlocks.BARREL_STEEL.get(),
                        NtmBlocks.BARREL_PLASTIC.get(),
                        NtmBlocks.BARREL_TCALLOY.get(),
                        NtmBlocks.BLOCK_BERYLLIUM.get(),
                        NtmBlocks.BLOCK_ACTINIUM.get(),
                        NtmBlocks.BLOCK_STEEL.get(),
                        NtmBlocks.BLOCK_ALUMINIUM.get(),
                        NtmBlocks.BLOCK_ASBESTOS.get(),
                        NtmBlocks.BLOCK_AUSTRALIUM.get(),
                        NtmBlocks.BLOCK_BISMUTH.get(),
                        NtmBlocks.BLOCK_CADMIUM.get(),
                        NtmBlocks.BLOCK_CDALLOY.get(),
                        NtmBlocks.BLOCK_COLTAN.get(),
                        NtmBlocks.BLOCK_COMBINE_STEEL.get(),
                        NtmBlocks.BLOCK_COPPER.get(),
                        NtmBlocks.BLOCK_DESH.get(),
                        NtmBlocks.BLOCK_DINEUTRONIUM.get(),
                        NtmBlocks.BLOCK_DURA_STEEL.get(),
                        NtmBlocks.BLOCK_EUPHEMIUM.get(),
                        NtmBlocks.BLOCK_FOAM.get(),
                        NtmBlocks.BLOCK_LANTHANIUM.get(),
                        NtmBlocks.BLOCK_LEAD.get(),
                        NtmBlocks.BLOCK_LITHIUM.get(),
                        NtmBlocks.BLOCK_MAGNETIZED_TUNGSTEN.get(),
                        NtmBlocks.BLOCK_METEOR_MOLTEN.get(),
                        NtmBlocks.BLOCK_MOX_FUEL.get(),
                        NtmBlocks.BLOCK_NEPTUNIUM.get(),
                        NtmBlocks.BLOCK_NIOBIUM.get(),
                        NtmBlocks.BLOCK_NITER.get(),
                        NtmBlocks.BLOCK_PLUTONIUM.get(),
                        NtmBlocks.BLOCK_PLUTONIUM_FUEL.get(),
                        NtmBlocks.BLOCK_POLONIUM.get(),
                        NtmBlocks.BLOCK_PU238.get(),
                        NtmBlocks.BLOCK_PU239.get(),
                        NtmBlocks.BLOCK_PU240.get(),
                        NtmBlocks.BLOCK_PU_MIX.get(),
                        NtmBlocks.BLOCK_RA226.get(),
                        NtmBlocks.BLOCK_RED_COPPER.get(),
                        NtmBlocks.BLOCK_SATURNITE.get(),
                        NtmBlocks.BLOCK_SCHRABIDATE.get(),
                        NtmBlocks.BLOCK_SCHRABIDIUM.get(),
                        NtmBlocks.BLOCK_SCHRABIDIUM_FUEL.get(),
                        NtmBlocks.BLOCK_SCHRARANIUM.get(),
                        NtmBlocks.BLOCK_SMORE.get(),
                        NtmBlocks.BLOCK_SOLINIUM.get(),
                        NtmBlocks.BLOCK_SULFUR.get(),
                        NtmBlocks.BLOCK_TANTALIUM.get(),
                        NtmBlocks.BLOCK_TCALLOY.get(),
                        NtmBlocks.BLOCK_THORIUM.get(),
                        NtmBlocks.BLOCK_THORIUM_FUEL.get(),
                        NtmBlocks.BLOCK_TITANIUM.get(),
                        NtmBlocks.BLOCK_TUNGSTEN.get(),
                        NtmBlocks.BLOCK_U233.get(),
                        NtmBlocks.BLOCK_U235.get(),
                        NtmBlocks.BLOCK_U238.get(),
                        NtmBlocks.BLOCK_URANIUM.get(),
                        NtmBlocks.BLOCK_URANIUM_FUEL.get(),
                        NtmBlocks.BLOCK_WASTE.get(),
                        NtmBlocks.BLOCK_WASTE_PAINTED.get(),
                        NtmBlocks.BLOCK_WASTE_VITRIFIED.get(),
                        NtmBlocks.BLOCK_YELLOWCAKE.get(),
                        NtmBlocks.BLOCK_FIBERGLASS.get(),
                        NtmBlocks.BLOCK_INSULATOR.get(),
                        NtmBlocks.BLOCK_SLAG.get(),
                        NtmBlocks.BLOCK_METEOR.get(),
                        NtmBlocks.BLOCK_METEOR_MOLTEN.get(),
                        NtmBlocks.BLOCK_METEOR_BROKEN.get(),
                        NtmBlocks.BLOCK_METEOR_COBBLE.get(),
                        NtmBlocks.BLOCK_METEOR_TREASURE.get(),

                        NtmBlocks.BASALT.get(),
                        NtmBlocks.BASALT_SMOOTH.get(),
                        NtmBlocks.BASALT_BRICK.get(),
                        NtmBlocks.BASALT_POLISHED.get(),
                        NtmBlocks.BASALT_TILES.get(),

                        NtmBlocks.ASPHALT.get(),
                        NtmBlocks.ASPHALT_LIGHT.get(),

                        NtmBlocks.BRICK_CONCRETE.get(),
                        NtmBlocks.BRICK_CONCRETE_MOSSY.get(),
                        NtmBlocks.BRICK_CONCRETE_CRACKED.get(),
                        NtmBlocks.BRICK_CONCRETE_BROKEN.get(),
                        NtmBlocks.BRICK_CONCRETE_MARKED.get(),
                        NtmBlocks.BRICK_OBSIDIAN.get(),
                        NtmBlocks.BRICK_LIGHT.get(),
                        NtmBlocks.BRICK_ASBESTOS.get(),
                        NtmBlocks.BLOCK_CORIUM.get(),
                        NtmBlocks.BLOCK_CORIUM_COBBLE.get(),
                        NtmBlocks.BRICK_FIRE.get(),
                        NtmBlocks.REINFORCED_LAMINATE.get(),
                        NtmBlocks.CONCRETE.get(),
                        NtmBlocks.CONCRETE_SMOOTH.get(),
                        NtmBlocks.CONCRETE_ASBESTOS.get(),
                        NtmBlocks.DUCRETE.get(),
                        NtmBlocks.DUCRETE_SMOOTH.get(),
                        NtmBlocks.DUCRETE_REINFORCED.get(),
                        NtmBlocks.DUCRETE_BRICK.get(),
                        NtmBlocks.STEEL_SCAFFOLD.get(),
                        NtmBlocks.GLASS_QUARTZ.get(),
                        NtmBlocks.STEEL_SCAFFOLD.get(),

                        NtmBlocks.BARBED_WIRE.get(),
                        NtmBlocks.SPIKES.get(),

                        NtmBlocks.BRICK_CONCRETE_STAIRS.get(),
                        NtmBlocks.BRICK_CONCRETE_MOSSY_STAIRS.get(),
                        NtmBlocks.BRICK_CONCRETE_CRACKED_STAIRS.get(),
                        NtmBlocks.BRICK_CONCRETE_BROKEN_STAIRS.get(),

                        NtmBlocks.BRICK_CONCRETE_SLAB.get(),
                        NtmBlocks.BRICK_CONCRETE_MOSSY_SLAB.get(),
                        NtmBlocks.BRICK_CONCRETE_CRACKED_SLAB.get(),
                        NtmBlocks.BRICK_CONCRETE_BROKEN_SLAB.get(),

                        NtmBlocks.REINFORCED_STONE.get(),
                        NtmBlocks.REINFORCED_BRICK.get(),
                        NtmBlocks.REINFORCED_SAND.get(),
                        NtmBlocks.REINFORCED_LIGHT.get(),
                        NtmBlocks.REINFORCED_LAMP.get(),
                        NtmBlocks.REINFORCED_GLASS.get(),
                        NtmBlocks.REINFORCED_GLASS_PANE.get(),
                        NtmBlocks.BRICK_COMPOUND.get(),

                        NtmBlocks.CONCRETE_SLAB.get(),
                        NtmBlocks.CONCRETE_SMOOTH_SLAB.get(),
                        NtmBlocks.CONCRETE_ASBESTOS_SLAB.get(),
                        NtmBlocks.REINFORCED_STONE_SLAB.get(),
                        NtmBlocks.REINFORCED_BRICK_SLAB.get(),
                        NtmBlocks.BRICK_LIGHT_SLAB.get(),
                        NtmBlocks.BRICK_COMPOUND_SLAB.get(),

                        NtmBlocks.CONCRETE_STAIRS.get(),
                        NtmBlocks.CONCRETE_SMOOTH_STAIRS.get(),
                        NtmBlocks.CONCRETE_ASBESTOS_STAIRS.get(),
                        NtmBlocks.REINFORCED_STONE_STAIRS.get(),
                        NtmBlocks.REINFORCED_BRICK_STAIRS.get(),
                        NtmBlocks.BRICK_LIGHT_STAIRS.get(),
                        NtmBlocks.BRICK_OBSIDIAN_STAIRS.get(),
                        NtmBlocks.BRICK_COMPOUND_STAIRS.get(),

                        NtmBlocks.DECO_PIPE.get(),
                        NtmBlocks.DECO_PIPE_RUSTED.get(),
                        NtmBlocks.DECO_PIPE_GREEN.get(),
                        NtmBlocks.DECO_PIPE_GREEN_RUSTED.get(),
                        NtmBlocks.DECO_PIPE_RED.get(),
                        NtmBlocks.DECO_PIPE_MARKED.get(),

                        NtmBlocks.DECO_PIPE_RIM.get(),
                        NtmBlocks.DECO_PIPE_RIM_RUSTED.get(),
                        NtmBlocks.DECO_PIPE_RIM_GREEN.get(),
                        NtmBlocks.DECO_PIPE_RIM_GREEN_RUSTED.get(),
                        NtmBlocks.DECO_PIPE_RIM_RED.get(),
                        NtmBlocks.DECO_PIPE_RIM_MARKED.get(),

                        NtmBlocks.DECO_PIPE_QUAD.get(),
                        NtmBlocks.DECO_PIPE_QUAD_RUSTED.get(),
                        NtmBlocks.DECO_PIPE_QUAD_GREEN.get(),
                        NtmBlocks.DECO_PIPE_QUAD_GREEN_RUSTED.get(),
                        NtmBlocks.DECO_PIPE_QUAD_RED.get(),
                        NtmBlocks.DECO_PIPE_QUAD_MARKED.get(),

                        NtmBlocks.DECO_PIPE_FRAMED.get(),
                        NtmBlocks.DECO_PIPE_FRAMED_RUSTED.get(),
                        NtmBlocks.DECO_PIPE_FRAMED_GREEN.get(),
                        NtmBlocks.DECO_PIPE_FRAMED_GREEN_RUSTED.get(),
                        NtmBlocks.DECO_PIPE_FRAMED_RED.get(),
                        NtmBlocks.DECO_PIPE_FRAMED_MARKED.get(),

                        NtmBlocks.METEOR_POLISHED.get(),
                        NtmBlocks.METEOR_BRICK.get(),
                        NtmBlocks.METEOR_BRICK_CHISELED.get(),
                        NtmBlocks.METEOR_PILLAR.get(),
                        NtmBlocks.METEOR_BATTERY.get(),
                        NtmBlocks.TILE_LAB.get(),
                        NtmBlocks.TILE_LAB_CRACKED.get(),
                        NtmBlocks.TILE_LAB_BROKEN.get(),
                        NtmBlocks.LIGHTSTONE.get(),
                        NtmBlocks.LIGHTSTONE_TILE.get(),
                        NtmBlocks.LIGHTSTONE_BRICKS.get(),
                        NtmBlocks.LIGHTSTONE_BRICKS_CHISELED.get(),
                        NtmBlocks.LIGHTSTONE_CHISELED.get(),
                        NtmBlocks.LIGHTSTONE_BRICKS_STAIRS.get(),

                        NtmBlocks.CONCRETE_WHITE.get(),
                        NtmBlocks.CONCRETE_ORANGE.get(),
                        NtmBlocks.CONCRETE_MAGENTA.get(),
                        NtmBlocks.CONCRETE_LIGHT_BLUE.get(),
                        NtmBlocks.CONCRETE_YELLOW.get(),
                        NtmBlocks.CONCRETE_LIME.get(),
                        NtmBlocks.CONCRETE_PINK.get(),
                        NtmBlocks.CONCRETE_GRAY.get(),
                        NtmBlocks.CONCRETE_LIGHT_GRAY.get(),
                        NtmBlocks.CONCRETE_CYAN.get(),
                        NtmBlocks.CONCRETE_PURPLE.get(),
                        NtmBlocks.CONCRETE_BLUE.get(),
                        NtmBlocks.CONCRETE_BROWN.get(),
                        NtmBlocks.CONCRETE_GREEN.get(),
                        NtmBlocks.CONCRETE_RED.get(),
                        NtmBlocks.CONCRETE_BLACK.get(),
                        NtmBlocks.CONCRETE_EXT_MACHINE.get(),
                        NtmBlocks.CONCRETE_EXT_MACHINE_STRIPE.get(),
                        NtmBlocks.CONCRETE_EXT_INDIGO.get(),
                        NtmBlocks.CONCRETE_EXT_PURPLE.get(),
                        NtmBlocks.CONCRETE_EXT_PINK.get(),
                        NtmBlocks.CONCRETE_EXT_HAZARD.get(),
                        NtmBlocks.CONCRETE_EXT_SAND.get(),
                        NtmBlocks.CONCRETE_EXT_BRONZE.get(),
                        NtmBlocks.CONCRETE_PILLAR.get(),
                        NtmBlocks.CONCRETE_REBAR.get(),
                        NtmBlocks.CONCRETE_SUPER.get(),
                        NtmBlocks.CONCRETE_SUPER_BROKEN.get(),

                        NtmBlocks.NUKE_GADGET.get(),
                        NtmBlocks.NUKE_LITTLE_BOY.get(),
                        NtmBlocks.NUKE_FAT_MAN.get(),
                        NtmBlocks.NUKE_IVY_MIKE.get(),
                        NtmBlocks.NUKE_TSAR_BOMBA.get(),
                        NtmBlocks.NUKE_PROTOTYPE.get(),
                        NtmBlocks.NUKE_FLEIJA.get(),
                        NtmBlocks.NUKE_SOLINIUM.get(),
                        NtmBlocks.NUKE_N2.get(),
                        NtmBlocks.NUKE_FSTBMB.get(),

                        NtmBlocks.SELLAFIELD_SLAKED.get(),
                        NtmBlocks.ORE_SELLAFIELD_EMERALD.get(),
                        NtmBlocks.ORE_SELLAFIELD_DIAMOND.get(),

                        NtmBlocks.PRESS_PREHEATER.get(),
                        NtmBlocks.MACHINE_PRESS.get(),
                        NtmBlocks.HEAT_BOILER.get(),
                        NtmBlocks.MACHINE_INDUSTRIAL_BOILER.get(),
                        NtmBlocks.HEATER_FIREBOX.get(),
                        NtmBlocks.HEATER_OVEN.get(),
                        NtmBlocks.HEATER_OILBURNER.get(),
                        NtmBlocks.HEATER_ELECTRIC.get(),
                        NtmBlocks.HEATER_HEATEX.get(),
                        NtmBlocks.MACHINE_SHREDDER.get(),
                        NtmBlocks.MACHINE_ELECTRIC_FURNACE.get(),
                        NtmBlocks.MACHINE_RTG_FURNACE.get(),
                        NtmBlocks.MACHINE_DIFURNACE_RTG.get(),
                        NtmBlocks.PWR_CONTROLLER.get(),
                        NtmBlocks.PWR_CASING.get(),
                        NtmBlocks.PWR_REFLECTOR.get(),
                        NtmBlocks.PWR_PORT.get(),
                        NtmBlocks.PWR_HEATEX.get(),
                        NtmBlocks.PWR_HEATSINK.get(),
                        NtmBlocks.PWR_NEUTRON_SOURCE.get(),
                        NtmBlocks.PWR_FUEL_CHANNEL.get(),
                        NtmBlocks.PWR_CONTROL.get(),
                        NtmBlocks.PWR_CHANNEL.get(),
                        NtmBlocks.PWR_BLOCK.get(),
                        NtmBlocks.WATZ.get(),
                        NtmBlocks.WATZ_PUMP.get(),
                        NtmBlocks.STRUCT_WATZ_CORE.get(),
                        NtmBlocks.WATZ_ELEMENT.get(),
                        NtmBlocks.WATZ_COOLER.get(),
                        NtmBlocks.WATZ_END.get(),
                        NtmBlocks.PILE_BRICK.get(),
                        NtmBlocks.PILE_BLOCK.get(),
                        NtmBlocks.PILE_LOADER.get(),
                        NtmBlocks.PILE_VENT.get(),
                        NtmBlocks.PILE_CONTROL.get(),
                        NtmBlocks.ICF.get(),
                        NtmBlocks.ICF_BLOCK.get(),
                        NtmBlocks.ICF_COMPONENT.get(),
                        NtmBlocks.ICF_LASER_COMPONENT.get(),
                        NtmBlocks.ICF_CONTROLLER.get(),
                        NtmBlocks.STRUCT_ICF.get(),
                        NtmBlocks.MACHINE_ICF_PRESS.get(),
                        NtmBlocks.FUSION_TORUS.get(),
                        NtmBlocks.FUSION_BREEDER.get(),
                        NtmBlocks.FUSION_COLLECTOR.get(),
                        NtmBlocks.FUSION_COUPLER.get(),
                        NtmBlocks.FUSION_BOILER.get(),
                        NtmBlocks.FUSION_MHDT.get(),
                        NtmBlocks.FUSION_KLYSTRON.get(),
                        NtmBlocks.FUSION_PLASMA_FORGE.get(),
                        NtmBlocks.FUSION_COMPONENT.get(),
                        NtmBlocks.REACTOR_RESEARCH.get(),
                        NtmBlocks.MACHINE_REACTOR_BREEDING.get(),
                        NtmBlocks.REACTOR_CONTROL.get(),
                        NtmBlocks.TURRET_SENTRY.get(),
                        NtmBlocks.TURRET_SENTRY_DAMAGED.get(),
                        NtmBlocks.TURRET_JEREMY.get(),
                        NtmBlocks.TURRET_HOWARD.get(),
                        NtmBlocks.TURRET_HOWARD_DAMAGED.get(),
                        NtmBlocks.TURRET_CHEKHOV.get(),
                        NtmBlocks.TURRET_FRIENDLY.get(),
                        NtmBlocks.WEAPON_TABLE.get(),
                        NtmBlocks.MACHINE_DIFURNACE.get(),
                        NtmBlocks.MACHINE_COMBUSTION_ENGINE.get(),
                        NtmBlocks.MACHINE_TURBINEGAS.get(),
                        NtmBlocks.MACHINE_TURBOFAN.get(),
                        NtmBlocks.MACHINE_CRYSTALLIZER.get(),
                        NtmBlocks.MACHINE_ASHPIT.get(),
                        NtmBlocks.CHIMNEY_BRICK.get(),
                        NtmBlocks.CHIMNEY_INDUSTRIAL.get(),
                        NtmBlocks.MACHINE_CONVERTER_HE_RF.get(),
                        NtmBlocks.MACHINE_CONVERTER_RF_HE.get(),
                        NtmBlocks.MACHINE_THRESHER.get(),
                        NtmBlocks.MACHINE_AUTOSAW.get(),
                        NtmBlocks.MACHINE_SAWMILL.get(),
                        NtmBlocks.MACHINE_RTG.get(),
                        NtmBlocks.MACHINE_CONDENSER.get(),
                        NtmBlocks.MACHINE_CONDENSER_POWERED.get(),
                        NtmBlocks.CABLE_DIODE.get(),
                        NtmBlocks.CABLE_DETECTOR.get(),
                        NtmBlocks.RED_CABLE_GAUGE.get(),
                        NtmBlocks.MACHINE_BATTERY_POTATO.get(),
                        NtmBlocks.MACHINE_BATTERY.get(),
                        NtmBlocks.MACHINE_LITHIUM_BATTERY.get(),
                        NtmBlocks.MACHINE_SCHRABIDIUM_BATTERY.get(),
                        NtmBlocks.MACHINE_DINEUTRONIUM_BATTERY.get(),
                        NtmBlocks.MACHINE_DIFURNACE_EXTENSION.get(),
                        NtmBlocks.RED_WIRE_COATED.get(),
                        NtmBlocks.STEEL_BEAM.get(),
                        NtmBlocks.STEEL_GRATE.get(),
                        NtmBlocks.STEEL_GRATE_WIDE.get(),
                        NtmBlocks.STEEL_WALL.get(),
                        NtmBlocks.STEEL_CORNER.get(),
                        NtmBlocks.STEEL_POLES.get(),
                        NtmBlocks.POLE_TOP.get(),
                        NtmBlocks.DECO_CRT_CLEAN.get(),
                        NtmBlocks.DECO_CRT_BROKEN.get(),
                        NtmBlocks.DECO_CRT_BLINKING.get(),
                        NtmBlocks.DECO_CRT_BSOD.get(),
                        NtmBlocks.DECO_TOASTER_IRON.get(),
                        NtmBlocks.DECO_TOASTER_STEEL.get(),
                        NtmBlocks.DECO_TOASTER_WOOD.get(),
                        NtmBlocks.TAPE_RECORDER.get(),
                        NtmBlocks.DECO_COMPUTER.get(),
                        NtmBlocks.BLOCK_STARMETAL.get(),
                        NtmBlocks.BLOCK_ELECTRICAL_SCRAP.get(),
                        NtmBlocks.STONE_GNEISS.get(),
                        NtmBlocks.CABLE_SWITCH.get(),
                        NtmBlocks.RED_CONNECTOR.get(),
                        NtmBlocks.RED_CONNECTOR_SUPER.get(),
                        NtmBlocks.RED_PYLON.get(),
                        NtmBlocks.RED_PYLON_STEEL.get(),
                        NtmBlocks.RED_PYLON_MEDIUM_WOOD.get(),
                        NtmBlocks.RED_PYLON_MEDIUM_WOOD_TRANSFORMER.get(),
                        NtmBlocks.RED_PYLON_MEDIUM_STEEL.get(),
                        NtmBlocks.RED_PYLON_MEDIUM_STEEL_TRANSFORMER.get(),
                        NtmBlocks.RED_PYLON_LARGE.get(),
                        NtmBlocks.SUBSTATION.get(),
                        NtmBlocks.MACHINE_DIESEL.get(),
                        NtmBlocks.MACHINE_COMPRESSOR.get(),
                        NtmBlocks.MACHINE_GAS_CENT.get(),
                        NtmBlocks.MACHINE_TOWER_SMALL.get(),
                        NtmBlocks.MACHINE_TOWER_LARGE.get(),
                        NtmBlocks.MACHINE_CYCLOTRON.get(),
                        NtmBlocks.MACHINE_PA_SOURCE.get(),
                        NtmBlocks.MACHINE_PA_BEAMLINE.get(),
                        NtmBlocks.MACHINE_PA_RFC.get(),
                        NtmBlocks.MACHINE_PA_QUADRUPOLE.get(),
                        NtmBlocks.MACHINE_PA_DIPOLE.get(),
                        NtmBlocks.MACHINE_PA_DETECTOR.get(),
                        NtmBlocks.MACHINE_EXPOSURE_CHAMBER.get(),
                        NtmBlocks.MACHINE_RAD_GEN.get(),
                        NtmBlocks.MACHINE_MINING_LASER.get(),
                        NtmBlocks.BARRICADE.get(),
                        NtmBlocks.MACHINE_COMPRESSOR_COMPACT.get(),
                        NtmBlocks.MACHINE_TURBINE.get(),
                        NtmBlocks.MACHINE_SOLAR_BOILER.get(),
                        NtmBlocks.SOLAR_MIRROR.get(),
                        NtmBlocks.FURNACE_IRON.get(),
                        NtmBlocks.FURNACE_STEEL.get(),
                        NtmBlocks.MACHINE_MIXER.get(),
                        NtmBlocks.MACHINE_ROCK_MILL.get(),
                        NtmBlocks.MACHINE_STEAM_ENGINE.get(),
                        NtmBlocks.MACHINE_STIRLING.get(),
                        NtmBlocks.MACHINE_SOLDERING_STATION.get(),
                        NtmBlocks.MACHINE_WELL.get(),
                        NtmBlocks.MACHINE_PUMPJACK.get(),
                        NtmBlocks.MACHINE_FRACKING_TOWER.get(),
                        NtmBlocks.MACHINE_REFINERY.get(),
                        NtmBlocks.MACHINE_BLAST_FURNACE.get(),
                        NtmBlocks.MACHINE_WOOD_BURNER.get(),
                        NtmBlocks.FURNACE_COMBINATION.get(),
                        NtmBlocks.MACHINE_DRAIN.get(),
                        NtmBlocks.MACHINE_INTAKE.get(),
                        NtmBlocks.PUMP_ELECTRIC.get(),
                        NtmBlocks.PUMP_STEAM.get(),
                        NtmBlocks.MACHINE_AUTOCRAFTER.get(),
                        NtmBlocks.MACHINE_EPRESS.get(),
                        NtmBlocks.MACHINE_FUNNEL.get(),
                        NtmBlocks.MACHINE_CENTRIFUGE.get(),
                        NtmBlocks.MACHINE_ARC_FURNACE.get(),
                        NtmBlocks.MACHINE_ROTARY_FURNACE.get(),
                        NtmBlocks.MACHINE_CRUCIBLE.get(),
                        NtmBlocks.FOUNDRY_CHANNEL.get(),
                        NtmBlocks.FOUNDRY_MOLD.get(),
                        NtmBlocks.FOUNDRY_BASIN.get(),
                        NtmBlocks.RBMK_GAUGE.get(),
                        NtmBlocks.RBMK_INDICATOR.get(),
                        NtmBlocks.RBMK_NUMITRON.get(),
                        NtmBlocks.RBMK_LEVER.get(),
                        NtmBlocks.RBMK_KEYPAD.get(),
                        NtmBlocks.RBMK_GRAPH.get(),
                        NtmBlocks.RBMK_DISPLAY.get(),
                        NtmBlocks.RBMK_TERMINAL.get(),
                        NtmBlocks.RBMK_DISPLAY_BLANK.get(),
                        NtmBlocks.RBMK_LOADER.get(),

                        NtmBlocks.CONVEYOR.get(),
                        NtmBlocks.CONVEYOR_EXPRESS.get(),
                        NtmBlocks.CONVEYOR_DOUBLE.get(),
                        NtmBlocks.CONVEYOR_TRIPLE.get(),
                        NtmBlocks.CONVEYOR_LIFT.get(),
                        NtmBlocks.CONVEYOR_CHUTE.get(),
                        NtmBlocks.CRANE_INSERTER.get(),
                        NtmBlocks.CRANE_EXTRACTOR.get(),
                        NtmBlocks.CRANE_GRABBER.get(),
                        NtmBlocks.CRANE_BOXER.get(),
                        NtmBlocks.CRANE_UNBOXER.get(),
                        NtmBlocks.CRANE_ROUTER.get(),
                        NtmBlocks.CRANE_PARTITIONER.get(),
                        NtmBlocks.CRANE_SPLITTER.get(),

                        NtmBlocks.DOOR_METAL.get(),
                        NtmBlocks.DOOR_OFFICE.get(),
                        NtmBlocks.DOOR_BUNKER.get(),
                        NtmBlocks.TRAPDOOR_STEEL.get(),
                        NtmBlocks.LADDER_STEEL.get(),
                        NtmBlocks.FENCE_METAL.get(),
                        NtmBlocks.FENCE_METAL_POST.get(),
                        NtmBlocks.DUNGEON_CHAIN.get(),
                        NtmBlocks.RAIL_NARROW.get(),
                        NtmBlocks.MACHINE_PUREX.get(),
                        NtmBlocks.MACHINE_RADIOLYSIS.get(),
                        NtmBlocks.MACHINE_CHEMICAL_PLANT.get(),
                        NtmBlocks.CRATE_IRON.get(),
                        NtmBlocks.CRATE_TUNGSTEN.get(),
                        NtmBlocks.CRATE_STEEL.get(),
                        NtmBlocks.CRATE_DESH.get(),
                        NtmBlocks.CRATE_TEMPLATE.get(),
                        NtmBlocks.TRANSFORMER.get(),

                        NtmBlocks.MACHINE_FLUID_TANK.get(),
                        NtmBlocks.MACHINE_BIGASSTANK.get(),
                        NtmBlocks.MACHINE_CHUNGUS.get(),
                        NtmBlocks.MACHINE_INDUSTRIAL_TURBINE.get(),
                        NtmBlocks.MACHINE_STRAND_CASTER.get(),
                        NtmBlocks.MACHINE_HEPHAESTUS.get(),
                        NtmBlocks.MACHINE_TELEPORTER.get(),
                        NtmBlocks.MACHINE_KEY_FORGE.get(),
                        NtmBlocks.MACHINE_DETECTOR.get(),
                        NtmBlocks.MACHINE_CHEMICAL_FACTORY.get(),
                        NtmBlocks.MACHINE_ASSEMBLY_FACTORY.get(),
                        NtmBlocks.MACHINE_BATTERY_REDD.get(),
                        NtmBlocks.MACHINE_BATTERY_SOCKET.get(),
                        NtmBlocks.MACHINE_ASSEMBLY_MACHINE.get(),
                        NtmBlocks.MACHINE_PRECASS.get(),
                        NtmBlocks.MACHINE_ORE_SLOPPER.get(),
                        NtmBlocks.MACHINE_EXCAVATOR.get(),
                        NtmBlocks.MACHINE_MISSILE_ASSEMBLY.get(),
                        NtmBlocks.LAUNCH_PAD.get(),
                        NtmBlocks.LAUNCH_PAD_LARGE.get(),
                        NtmBlocks.SOYUZ_LAUNCHER.get(),
                        NtmBlocks.MACHINE_RADAR.get(),
                        NtmBlocks.MACHINE_RADAR_LARGE.get(),
                        NtmBlocks.MACHINE_SATLINKER.get(),
                        NtmBlocks.MACHINE_SAT_LINK.get(),
                        NtmBlocks.MACHINE_SAT_DOCK.get(),
                        NtmBlocks.MACHINE_TAPE_DRIVE.get(),
                        NtmBlocks.MACHINE_SUPER_COMPUTER.get(),
                        NtmBlocks.MACHINE_AMMO_PRESS.get(),
                        NtmBlocks.RADAR_SCREEN.get(),
                        NtmBlocks.MACHINE_SIREN.get(),
                        NtmBlocks.MACHINE_ANNIHILATOR.get(),
                        NtmBlocks.ANVIL.get(),

                        /*
                         * Runde 156. Diese einundvierzig Bloecke sind mit requiresCorrectToolForDrops
                         * angemeldet und standen in keinem mineable-Tag. In 1.21 entscheidet allein der
                         * Tag darueber, ob ein Werkzeug als das richtige gilt: passt keine Regel des
                         * Werkzeugs, liefert Tool.isCorrectForDrops falsch, und der Block faellt mit
                         * KEINEM Werkzeug. Alle einundvierzig haben eine dropSelf-Tabelle, waren also
                         * sehr wohl zum Abbauen gedacht -- die ganze RBMK-Saeule eingeschlossen.
                         */
                        NtmBlocks.MACHINE_ARC_WELDER.get(),
                        NtmBlocks.MACHINE_FRACTION_TOWER.get(),
                        NtmBlocks.FRACTION_SPACER.get(),
                        NtmBlocks.MACHINE_CATALYTIC_REFORMER.get(),
                        NtmBlocks.MACHINE_HYDROTREATER.get(),
                        NtmBlocks.MACHINE_VACUUM_DISTILL.get(),
                        NtmBlocks.MACHINE_PYRO_OVEN.get(),
                        NtmBlocks.MACHINE_CATALYTIC_CRACKER.get(),
                        NtmBlocks.MACHINE_COKER.get(),
                        NtmBlocks.MACHINE_GAS_FLARE.get(),
                        NtmBlocks.MACHINE_LIQUEFACTOR.get(),
                        NtmBlocks.MACHINE_SOLIDIFIER.get(),
                        NtmBlocks.RBMK_BLANK.get(),
                        NtmBlocks.RBMK_MODERATOR.get(),
                        NtmBlocks.RBMK_ABSORBER.get(),
                        NtmBlocks.RBMK_REFLECTOR.get(),
                        NtmBlocks.RBMK_ROD.get(),
                        NtmBlocks.RBMK_ROD_MOD.get(),
                        NtmBlocks.RBMK_CONTROL.get(),
                        NtmBlocks.RBMK_CONTROL_MOD.get(),
                        NtmBlocks.RBMK_CONTROL_AUTO.get(),
                        NtmBlocks.RBMK_CONTROL_REASIM.get(),
                        NtmBlocks.RBMK_CONTROL_REASIM_AUTO.get(),
                        NtmBlocks.RBMK_ROD_REASIM.get(),
                        NtmBlocks.RBMK_ROD_REASIM_MOD.get(),
                        NtmBlocks.RBMK_BOILER.get(),
                        NtmBlocks.RBMK_COOLER.get(),
                        NtmBlocks.RBMK_STORAGE.get(),
                        NtmBlocks.RBMK_HEATER.get(),
                        NtmBlocks.RBMK_STEAM_INLET.get(),
                        NtmBlocks.RBMK_STEAM_OUTLET.get(),
                        NtmBlocks.RBMK_OUTGASSER.get(),
                        NtmBlocks.RBMK_CONSOLE.get(),
                        NtmBlocks.RBMK_CRANE_CONSOLE.get(),
                        NtmBlocks.RBMK_AUTOLOADER.get(),
                        NtmBlocks.RBMK_DEBRIS.get(),
                        NtmBlocks.RBMK_DEBRIS_BURNING.get(),
                        NtmBlocks.RBMK_DEBRIS_DIGAMMA.get(),
                        NtmBlocks.RBMK_DEBRIS_RADIATING.get(),
                        NtmBlocks.MACHINE_WASTE_DRUM.get(),
                        NtmBlocks.EMP_BOMB.get()
                );

        this.tag(BlockTags.ANVIL).add(NtmBlocks.ANVIL.get());

        this.tag(BlockTags.MINEABLE_WITH_AXE)
                .add(
                        NtmBlocks.WASTE_LOG.get(),
                        NtmBlocks.WASTE_PLANKS.get(),
                        NtmBlocks.FROZEN_LOG.get(),
                        NtmBlocks.FROZEN_PLANKS.get(),
                        NtmBlocks.WOOD_BARRIER.get(),
                        NtmBlocks.WOOD_STRUCTURE_ROOF.get(),
                        NtmBlocks.WOOD_STRUCTURE_SCAFFOLD.get(),
                        NtmBlocks.WOOD_STRUCTURE_CEILING.get()
                );

        this.tag(BlockTags.MINEABLE_WITH_SHOVEL)
                .add(
                        NtmBlocks.WASTE_EARTH.get(),
                        NtmBlocks.WASTE_MYCELIUM.get(),
                        NtmBlocks.WASTE_TRINITITE.get(),
                        NtmBlocks.WASTE_TRINITITE_RED.get(),
                        NtmBlocks.FROZEN_DIRT.get(),
                        NtmBlocks.FROZEN_GRASS.get(),
                        NtmBlocks.FALLOUT.get(),
                        NtmBlocks.MOON_TURF.get(),
                        NtmBlocks.SAND_QUARTZ.get(),
                        NtmBlocks.NTM_DIRT.get()

                );

        this.tag(BlockTags.MINEABLE_WITH_HOE)
                .add(
                        NtmBlocks.WASTE_LEAVES.get(),
                        NtmBlocks.LEAVES_LAYER.get()
                );

        /* Im Original ist der Sternmetallblock ein BlockBeaconable -- in 1.21 macht das
         * der Tag. */
        this.tag(BlockTags.BEACON_BASE_BLOCKS).add(NtmBlocks.BLOCK_STARMETAL.get());

        // vanilla compat
        this.tag(BlockTags.STRIDER_WARM_BLOCKS).add(NtmBlocks.VOLCANIC_LAVA.get());
    }
}
