package com.hbm.items.machine;

import com.hbm.config.VersatileConfig;
import com.hbm.interfaces.HalfLifeType;
import com.hbm.inventory.MetaHelper;
import com.hbm.items.EnumMultiItem;
import com.hbm.items.NtmItems;
import com.hbm.items.machine.RTGPelletDepletedItem.DepletedRTGMaterial;
import com.hbm.util.EnumUtil;
import com.hbm.util.RTGUtil;
import com.hbm.util.TagsUtil;
import com.hbm.util.i18n.I18nUtil;
import net.minecraft.ChatFormatting;
import net.minecraft.nbt.CompoundTag;
import net.minecraft.network.chat.Component;
import net.minecraft.sounds.SoundEvents;
import net.minecraft.sounds.SoundSource;
import net.minecraft.util.Mth;
import net.minecraft.world.InteractionHand;
import net.minecraft.world.InteractionResultHolder;
import net.minecraft.world.entity.player.Player;
import net.minecraft.world.item.ItemStack;
import net.minecraft.world.item.TooltipFlag;
import net.minecraft.world.level.Level;

import java.text.NumberFormat;
import java.util.List;
import java.util.Locale;

/**
 * Portiert aus 1.7.10: com.hbm.items.machine.ItemRTGPellet.
 *
 * Im Original war jedes Pellet ein eigenes Item (pellet_rtg, pellet_rtg_radium, ...),
 * das ueber den Konstruktor seine Zerfallswaerme und ueber setDecays() sein Zerfallsziel
 * samt Lebensdauer bekam. Im Port liegen die Untertypen als Metadaten auf einem einzigen
 * Item -- EnumMultiItem plus MetaHelper, genau wie bei PistonsItem.
 *
 * Zahlenwerte (Waerme, Halbwertszeiten, Faktor 1.5) sind unveraendert aus
 * ModItems.mainRegistry() uebernommen.
 */
public class RTGPelletItem extends EnumMultiItem {

    /** NBT-Schluessel der Restlebensdauer, Name wie im Original. */
    public static final String KEY_DEPLETION = "PELLET_DEPLETION";

    public RTGPelletItem(Properties properties) {
        super(properties, RTGPelletType.class, true, true);
    }

    /** Wortgleich aus dem Original uebernommen. */
    private static final String[] FACTS = new String[] {
            "One gram of Pu-238 costs $8,000.",
            "One gram of Pu-238 produces just under half a Watt of decay heat.",
            "The typical plutonium RTG contains close to eight kilograms of Pu-238.",
            "Pu-238's half life is 87.7 years.",
            "A plutonium RTG was used to power the New Horizons probe that visited Pluto in 2015.",
            "Po-210 can also be used for RTGs as it generates 140 W/g of decay heat due to its 138 day half life.",
            "Pa-231 is an isotope of protactinium that easily fissions, but it isn't quite fissile.",
            "Muons generated by matter-antimatter reactions can trigger nuclear fusion reactions at room temperature.",
            "Roughly 20% of U-235 nuclei will fail to fission when hit by a neutron. They become U-236 nuclei instead.",
            "Thorium reactors are really uranium reactors that convert thorium into U-233.",
            "Natural uranium consists of 99.284% U-238, 0.711% U-235, and 0.0055% U-234.",
            "Most nuclear reactors use uranium that has been enriched to 3-5% U-235.",
            "Uranium-based nuclear weapons require uranium enriched to at least 85-90% U-235.",
            "Depleted uranium is uranium that has had most of its U-235 removed. It is effectively pure U-238.",
            "In the 1920s, uranium was considered a useless byproduct of the production of radium.",
            "The Manhattan Project referred to refined natural uranium as tuballoy, enriched uranium as oralloy, and depleted uranium as depletalloy."
    };

    /** Untertyp eines Stacks, notfalls auf einen gueltigen Wert zurechtgebogen. */
    public static RTGPelletType getType(ItemStack stack) {
        return EnumUtil.grabEnumSafely(RTGPelletType.class, MetaHelper.getMeta(stack));
    }

    /** Zerfallswaerme des Untertyps in HE/t, vor der Skalierung durch den Zerfall. */
    public static short getHeat(ItemStack stack) {
        return getType(stack).getHeat();
    }

    public static long getMaxLifespan(ItemStack stack) {
        return getType(stack).lifespan;
    }

    public static boolean getDoesDecay(ItemStack stack) {
        return getType(stack).doesDecay();
    }

    /** Kopie des Zerfallsprodukts, oder ein leerer Stack wenn der Typ nicht zerfaellt. */
    public static ItemStack getDecayItem(ItemStack stack) {
        RTGPelletType type = getType(stack);
        if(type.decayInto == null) return ItemStack.EMPTY;
        return MetaHelper.newStack(NtmItems.PELLET_RTG_DEPLETED.get(), 1, type.decayInto.ordinal());
    }

    /**
     * Laesst das Pellet um einen Tick altern. Ist es aufgebraucht, kommt das
     * Zerfallsprodukt zurueck, sonst der uebergebene Stack. 1:1 aus dem Original.
     */
    public static ItemStack handleDecay(ItemStack stack) {
        if(getDoesDecay(stack) && VersatileConfig.rtgDecay()) {
            if(getLifespan(stack) <= 0) return getDecayItem(stack);
            else decay(stack);
        }

        return stack;
    }

    /**
     * Zaehlt die Restlebensdauer um eins herunter. Hat der Stack noch keinen Eintrag,
     * wird -- wie im Original -- nur die volle Lebensdauer hineingeschrieben, ohne
     * schon abzuziehen.
     */
    public static void decay(ItemStack stack) {
        if(!(stack.getItem() instanceof RTGPelletItem)) return;
        if(!getDoesDecay(stack)) return;

        CompoundTag tag = TagsUtil.getCustomData(stack);

        if(tag.contains(KEY_DEPLETION)) {
            tag.putLong(KEY_DEPLETION, tag.getLong(KEY_DEPLETION) - 1);
        } else {
            tag.putLong(KEY_DEPLETION, getMaxLifespan(stack));
        }

        TagsUtil.putCustomData(stack, tag);
    }

    /** Restlebensdauer in Ticks; fehlt der Eintrag noch, wird er mit dem Maximum angelegt. */
    public static long getLifespan(ItemStack stack) {
        if(!(stack.getItem() instanceof RTGPelletItem)) return 0;

        CompoundTag tag = TagsUtil.getCustomData(stack);

        if(tag.contains(KEY_DEPLETION)) return tag.getLong(KEY_DEPLETION);

        long max = getMaxLifespan(stack);
        tag.putLong(KEY_DEPLETION, max);
        TagsUtil.putCustomData(stack, tag);
        return max;
    }

    /** Leistung nach Abzug des bisherigen Zerfalls. */
    public static short getScaledPower(ItemStack stack) {
        RTGPelletType type = getType(stack);
        if(type.lifespan <= 0) return type.getHeat();
        return (short) Math.ceil(type.getHeat() * ((double) getLifespan(stack) / (double) type.lifespan));
    }

    @Override
    public InteractionResultHolder<ItemStack> use(Level level, Player player, InteractionHand usedHand) {
        ItemStack stack = player.getItemInHand(usedHand);

        // Nur das Plutoniumpellet plaudert -- im Original "this == ModItems.pellet_rtg".
        if(!level.isClientSide && getType(stack) == RTGPelletType.PU238) {
            player.sendSystemMessage(Component.literal(FACTS[level.random.nextInt(FACTS.length)]).withStyle(ChatFormatting.YELLOW));
            // Serverseitig verteilt, damit alle in Hoerweite den Ton bekommen.
            level.playSound(null, player.getX(), player.getY(), player.getZ(), SoundEvents.EXPERIENCE_ORB_PICKUP, SoundSource.PLAYERS, 1.0F, 1.0F);
        }

        return InteractionResultHolder.pass(stack);
    }

    @Override
    public boolean isBarVisible(ItemStack stack) {
        return getDoesDecay(stack) && getLifespan(stack) != getMaxLifespan(stack);
    }

    @Override
    public int getBarWidth(ItemStack stack) {
        long max = getMaxLifespan(stack);
        if(max <= 0) return 13;
        return Math.round(13F * (float) ((double) getLifespan(stack) / (double) max));
    }

    @Override
    public int getBarColor(ItemStack stack) {
        long max = getMaxLifespan(stack);
        float remaining = max <= 0 ? 1F : (float) ((double) getLifespan(stack) / (double) max);
        return Mth.hsvToRgb(remaining / 3F, 1.0F, 1.0F);
    }

    @Override
    public void appendHoverText(ItemStack stack, TooltipContext context, List<Component> components, TooltipFlag flag) {

        RTGPelletType type = getType(stack);

        components.add(Component.translatable(this.getDescriptionId(stack) + ".desc"));
        components.add(Component.literal(I18nUtil.resolveKey("desc.item.rtgHeat",
                type.doesDecay() && VersatileConfig.scaleRTGPower() ? getScaledPower(stack) : type.getHeat())));

        if(type.doesDecay()) {
            ItemStack decayItem = getDecayItem(stack);
            components.add(Component.literal(I18nUtil.resolveKey("desc.item.rtgDecay",
                    decayItem.getHoverName().getString(), decayItem.getCount())));
            components.add(Component.literal(toPercentage(getLifespan(stack), type.lifespan)));

            if(flag.isAdvanced()) {
                components.add(Component.literal("EXTENDED INFO:"));
                components.add(Component.literal(String.format(Locale.US, "%s / %s ticks", getLifespan(stack), type.lifespan)));
                String[] timeLeft = ticksToDate(getLifespan(stack));
                String[] maxLife = ticksToDate(type.lifespan);
                components.add(Component.literal(String.format(Locale.US, "Time remaining: %s y, %s d, %s h", (Object[]) timeLeft)));
                components.add(Component.literal(String.format(Locale.US, "Maximum life: %s y, %s d, %s h", (Object[]) maxLife)));
            }
        }
    }

    /**
     * Entspricht BobMathUtil.toPercentage aus 1.7.10. Die Methode fehlt im Port,
     * deshalb steht sie hier lokal -- Rechenweg unveraendert.
     */
    private static String toPercentage(float amount, float total) {
        return NumberFormat.getPercentInstance().format(amount / total);
    }

    /**
     * Entspricht BobMathUtil.ticksToDate samt convertScale aus 1.7.10, ebenfalls
     * unveraendert, weil beides im Port fehlt.
     */
    private static String[] ticksToDate(long ticks) {

        int tickDay = 48000;
        int tickYear = tickDay * 100;

        String[] dateOut = new String[3];
        long year = Math.floorDiv(ticks, tickYear);
        byte day = (byte) Math.floorDiv(ticks - (long) tickYear * year, tickDay);
        float time = ticks - ((long) tickYear * year + (long) tickDay * day);
        time = (float) convertScale(time, 0, tickDay, 0, 10F);
        dateOut[0] = String.valueOf(year);
        dateOut[1] = String.valueOf(day);
        dateOut[2] = String.valueOf(time);
        return dateOut;
    }

    private static double convertScale(double toScale, double oldMin, double oldMax, double newMin, double newMax) {
        double prevRange = oldMax - oldMin;
        double newRange = newMax - newMin;
        return (((toScale - oldMin) * newRange) / prevRange) + newMin;
    }

    /**
     * Die Untertypen. Reihenfolge wie in ModItems.mainRegistry(), nur das
     * Plutoniumpellet steht vorne: Metadaten 0 ist das Symbol des Kreativreiters und
     * im Port hiess das Grunditem "pellet_rtg" schon immer das Plutoniumpellet.
     *
     * Die Lebensdauer ist ueberall RTGUtil.getLifespan(Halbwertszeit, Einheit, false) * 1.5,
     * genau wie im Original.
     */
    public enum RTGPelletType {

        PU238       (10,  DepletedRTGMaterial.LEAD,       87.7F, HalfLifeType.MEDIUM),
        RADIUM      (3,   DepletedRTGMaterial.LEAD,       16.0F, HalfLifeType.LONG),
        WEAK        (5,   DepletedRTGMaterial.LEAD,       1.0F,  HalfLifeType.LONG),
        STRONTIUM   (15,  DepletedRTGMaterial.ZIRCONIUM,  29.0F, HalfLifeType.MEDIUM),
        COBALT      (15,  DepletedRTGMaterial.NICKEL,     5.3F,  HalfLifeType.MEDIUM),
        ACTINIUM    (20,  DepletedRTGMaterial.LEAD,       21.8F, HalfLifeType.MEDIUM),
        AMERICIUM   (20,  DepletedRTGMaterial.NEPTUNIUM,  4.7F,  HalfLifeType.LONG),
        POLONIUM    (50,  DepletedRTGMaterial.LEAD,       138.0F, HalfLifeType.SHORT),
        GOLD        (100, 200, DepletedRTGMaterial.MERCURY, 2.7F, HalfLifeType.SHORT),
        LEAD        (200, 600, DepletedRTGMaterial.BISMUTH, 0.3F, HalfLifeType.SHORT);

        /** Waerme ohne aktivierten Zerfall. */
        public final short heat;
        /** Waerme bei aktiviertem Zerfall -- nur Gold und Blei weichen ab. */
        public final short heatDecaying;
        public final DepletedRTGMaterial decayInto;
        public final long lifespan;

        RTGPelletType(int heat, DepletedRTGMaterial decayInto, float halfLife, HalfLifeType type) {
            this(heat, heat, decayInto, halfLife, type);
        }

        RTGPelletType(int heat, int heatDecaying, DepletedRTGMaterial decayInto, float halfLife, HalfLifeType type) {
            this.heat = (short) heat;
            this.heatDecaying = (short) heatDecaying;
            this.decayInto = decayInto;
            this.lifespan = (long) (RTGUtil.getLifespan(halfLife, type, false) * 1.5);
        }

        public short getHeat() {
            return VersatileConfig.rtgDecay() ? this.heatDecaying : this.heat;
        }

        public boolean doesDecay() {
            return this.decayInto != null;
        }
    }
}
